name: Build and Push Docker Image

on:
  workflow_dispatch:  # only run when manually triggered
  
env:
  ACR_NAME: "rshinycr"
  ACR_LOGIN_SERVER: "rshinycr.azurecr.io"
  IMAGE_NAME: "todo-app"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build and push Docker image
        run: |
          echo "🐳 Build and push Docker image to $ACR_LOGIN_SERVER"
          az acr login --name $ACR_NAME
          docker build \
            --build-arg GITHUB_PAT=${{ secrets.GITHUB1_PAT }} \
            --build-arg GITHUB2_PAT=${{ secrets.GITHUB2_PAT }} \
            -t $ACR_LOGIN_SERVER/$IMAGE_NAME:latest .
          docker push $ACR_LOGIN_SERVER/$IMAGE_NAME:latest
