name: Build, Test and Push Docker Image

on:
  workflow_dispatch:  # only run when manually triggered
  
env:
  ACR_NAME: "rshinycr"
  ACR_LOGIN_SERVER: "rshinycr.azurecr.io"
  IMAGE_NAME: "todo-app"

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build Docker image (with tests)
        run: |
          echo "Building Docker image with test environment"
          az acr login --name $ACR_NAME
          docker build \
            --build-arg GITHUB1_PAT=${{ secrets.GITHUB1_PAT }} \
            --build-arg GITHUB2_PAT=${{ secrets.GITHUB2_PAT }} \
            -t $ACR_LOGIN_SERVER/$IMAGE_NAME:latest .

      - name: Run tests inside Docker container
        run: |
          echo "Running R testthat & shinytest2 inside container"
          docker run --rm \
            -e ENVIRONMENT=ci \
            -v ${{ github.workspace }}/tests:/tests \
            $ACR_LOGIN_SERVER/$IMAGE_NAME:latest \
            Rscript -e "testthat::test_dir('/tests/testthat')"

      - name: Push Docker image to ACR
        run: |
          echo "Pushing Docker image to Azure Container Registry"
          docker push $ACR_LOGIN_SERVER/$IMAGE_NAME:latest