name: Deploy RShiny App (Skip Build)

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'Dockerfile'
      - 'requirements.txt'
      - 'scripts/**'
      - '.github/workflows/build-image.yml'
  workflow_dispatch:

env:
  RESOURCE_GROUP: "r-shiny-rg"
  LOCATION: "australiasoutheast"
  ACR_LOGIN_SERVER: "rshinycr.azurecr.io"
  WEBAPP_NAME: "shiny-web-app"
  KEYVAULT_NAME: "my-shiny-keyvault"
  SECRET_NAME: "aad-client-secret"
  IMAGE_NAME: "todo-app"
  AAD_CLIENT_ID: ${{ secrets.AAD_CLIENT_ID }}
  AAD_ISSUER_URL: "https://sts.windows.net/${{ secrets.AZURE_TENANT_ID }}/"
  TOKEN_AUDIENCE: "api://${{ secrets.AAD_CLIENT_ID }}"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Update container settings for App Service
        run: |
          echo "🔄 Update container settings for Web App"
          az webapp config container set \
            --name $WEBAPP_NAME \
            --resource-group $RESOURCE_GROUP \
            --docker-custom-image-name $ACR_LOGIN_SERVER/$IMAGE_NAME:latest \
            --docker-registry-server-url https://$ACR_LOGIN_SERVER

      - name: Configure Key Vault references in App Service
        run: |
          echo "🔑 Configure Key Vault references in App Service"
          az webapp config appsettings set \
            --name $WEBAPP_NAME \
            --resource-group $RESOURCE_GROUP \
            --settings \
              "AAD_CLIENT_SECRET=@Microsoft.KeyVault(SecretUri=https://$KEYVAULT_NAME.vault.azure.net/secrets/$SECRET_NAME/)"

      - name: Configure Azure AD Authentication
        run: |
          echo "🔐 Configure Azure AD Authentication"
          az webapp auth update \
            --name $WEBAPP_NAME \
            --resource-group $RESOURCE_GROUP \
            --enabled true \
            --action LoginWithAzureActiveDirectory \
            --aad-client-id "${{ secrets.AAD_CLIENT_ID }}" \
            --aad-token-issuer-url "https://sts.windows.net/${{ secrets.AZURE_TENANT_ID }}/" \
            --aad-allowed-token-audiences "api://${{ secrets.AAD_CLIENT_ID }}" \
            --token-store false \
            --login-parameters "prompt=select_account&domain_hint=consumers"

      - name: Restart App Service
        run: |
          echo "🔄 Restart App Service to apply changes"
          az webapp restart --name $WEBAPP_NAME --resource-group $RESOURCE_GROUP
