name: Deploy RShiny App (Skip Build)

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'Dockerfile'
      - 'scripts/**'
      - '.github/workflows/build-image.yml'
      - 'ReadMe.md'
  workflow_dispatch: # allow manually triggered

env:
  RESOURCE_GROUP: "r-shiny-rg"
  LOCATION: "australiasoutheast"
  ACR_LOGIN_SERVER: "rshinycr.azurecr.io"
  WEBAPP_NAME: "shiny-web-app"
  KEYVAULT_NAME: "my-shiny-keyvault"
  SECRET_NAME: "aad-client-secret"
  IMAGE_NAME: "todo-app"
  AAD_CLIENT_ID: ${{ secrets.AAD_CLIENT_ID }}
  AAD_ISSUER_URL: "https://sts.windows.net/${{ secrets.AZURE_TENANT_ID }}/"
  TOKEN_AUDIENCE: "api://${{ secrets.AAD_CLIENT_ID }}"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Install authV2 Azure CLI extension
        run: az extension add --name authV2 --yes

      - name: Update container settings for App Service
        run: |
          echo "Update container settings for Web App"
          az webapp config container set \
            --name $WEBAPP_NAME \
            --resource-group $RESOURCE_GROUP \
            --docker-custom-image-name $ACR_LOGIN_SERVER/$IMAGE_NAME:latest \
            --docker-registry-server-url https://$ACR_LOGIN_SERVER

      - name: Configure Key Vault references in App Service
        run: |
          echo "Configure Key Vault references in App Service"
          az webapp config appsettings set \
            --name $WEBAPP_NAME \
            --resource-group $RESOURCE_GROUP \
            --settings \
              "AAD_CLIENT_SECRET=@Microsoft.KeyVault(SecretUri=https://$KEYVAULT_NAME.vault.azure.net/secrets/$SECRET_NAME/)"

      - name: Configure Azure AD Authentication
        run: |
          echo "Configure Azure AD Authentication"
          echo "Enabling AuthV2 and setting token store to false"
          az webapp auth update \
            --name $WEBAPP_NAME \
            --resource-group $RESOURCE_GROUP \
            --enabled true \
            --unauthenticated-client-action AllowAnonymous \
            --enable-token-store false

          echo "Configuring Microsoft Identity Provider"
          az webapp auth microsoft update \
            --name $WEBAPP_NAME \
            --resource-group $RESOURCE_GROUP \
            --client-id "${{ secrets.AAD_CLIENT_ID }}" \
            --issuer "https://sts.windows.net/${{ secrets.AZURE_TENANT_ID }}/" \
            --allowed-audiences "api://${{ secrets.AAD_CLIENT_ID }}" \
            --yes
          
          echo "Setting default provider to AzureActiveDirectory and unauthenticated client action"
          az webapp auth update \
            --name $WEBAPP_NAME \
            --resource-group $RESOURCE_GROUP \
            --redirect-provider AzureActiveDirectory \
            --unauthenticated-client-action RedirectToLoginPage

      - name: Restart App Service
        run: |
          echo "Restart App Service to apply changes"
          az webapp restart --name $WEBAPP_NAME --resource-group $RESOURCE_GROUP

      - name: Verify deployment
        run: |
          echo "Verify deployment"
          APP_URL=$(az webapp show --name $WEBAPP_NAME --resource-group $RESOURCE_GROUP --query defaultHostName -o tsv)
          echo "Application deployed at: https://$APP_URL"
          sleep 30
          curl -s -o /dev/null -w "%{http_code}" https://$APP_URL/health || echo "Application may need more time to start"